name: autofrhodo
channels:
  - numba
  - cantera/label/dev
  - conda-forge
  - defaults
dependencies:
  # Dependencies related to Fhrodo
  #  Eventually, these will be installed via pip
  - cantera=2.6.0a1
  - ipopt=3.14.*
  - matplotlib=3.5.1
  - nlopt=2.7.0
  - numba=0.54.1
  - numpy=1.20.3
  - pip
  - pygmo=2.18.0
  - pyqt=5.12.3
  - qt=5.12.9
  - qtpy=1.11.2
  - requests=2.27.1
  - scipy=1.5.*
  - tabulate=0.8.9
  - pytest

  # Related to the planning components
  - pandas>=1.4
  - kombine>=0.8
  - jupyterlab

  - pip:

    # Frhodo-related libraries
    - dtcwt==0.12.0
    - rbfopt==4.2.2
    - -e ../Frhodo  # Hard-coded to my local dev environment for now
